db-uri = "postgres://luna_user:doi_mat_khau_manh@127.0.0.1:5432/luna_jewel"
db-schemas = "public"
db-anon-role = "web_anon"
jwt-secret = "0KdgneV00PHu1vprueueQ3qpxXjxq-tkvaTu13F3KoOjVAyN4-RyF5Zil1T2aRId"
server-host = "127.0.0.1"
server-port = 3000
