/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YeuThichRouteImport } from './routes/yeu-thich'
import { Route as ThuVongCoRouteImport } from './routes/thu-vong-co'
import { Route as ThongBaoRouteImport } from './routes/thong-bao'
import { Route as ThanhToanRouteImport } from './routes/thanh-toan'
import { Route as TaiKhoanRouteImport } from './routes/tai-khoan'
import { Route as HuongDanThanhToanRouteImport } from './routes/huong-dan-thanh-toan'
import { Route as HuongDanMuaHangRouteImport } from './routes/huong-dan-mua-hang'
import { Route as HoTroRouteImport } from './routes/ho-tro'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as GioHangRouteImport } from './routes/gio-hang'
import { Route as DonHangRouteImport } from './routes/don-hang'
import { Route as DieuKhoanDichVuRouteImport } from './routes/dieu-khoan-dich-vu'
import { Route as DichVuRouteImport } from './routes/dich-vu'
import { Route as ChinhSachVanChuyenRouteImport } from './routes/chinh-sach-van-chuyen'
import { Route as ChinhSachDoiTraRouteImport } from './routes/chinh-sach-doi-tra'
import { Route as ChinhSachBaoMatRouteImport } from './routes/chinh-sach-bao-mat'
import { Route as ChinhSachBaoHanhRouteImport } from './routes/chinh-sach-bao-hanh'
import { Route as BoSuuTapRouteImport } from './routes/bo-suu-tap'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SanPhamSlugRouteImport } from './routes/san-pham.$slug'

const YeuThichRoute = YeuThichRouteImport.update({
  id: '/yeu-thich',
  path: '/yeu-thich',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuVongCoRoute = ThuVongCoRouteImport.update({
  id: '/thu-vong-co',
  path: '/thu-vong-co',
  getParentRoute: () => rootRouteImport,
} as any)
const ThongBaoRoute = ThongBaoRouteImport.update({
  id: '/thong-bao',
  path: '/thong-bao',
  getParentRoute: () => rootRouteImport,
} as any)
const ThanhToanRoute = ThanhToanRouteImport.update({
  id: '/thanh-toan',
  path: '/thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiKhoanRoute = TaiKhoanRouteImport.update({
  id: '/tai-khoan',
  path: '/tai-khoan',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanThanhToanRoute = HuongDanThanhToanRouteImport.update({
  id: '/huong-dan-thanh-toan',
  path: '/huong-dan-thanh-toan',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanMuaHangRoute = HuongDanMuaHangRouteImport.update({
  id: '/huong-dan-mua-hang',
  path: '/huong-dan-mua-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const HoTroRoute = HoTroRouteImport.update({
  id: '/ho-tro',
  path: '/ho-tro',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangRoute = GioHangRouteImport.update({
  id: '/gio-hang',
  path: '/gio-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const DonHangRoute = DonHangRouteImport.update({
  id: '/don-hang',
  path: '/don-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuKhoanDichVuRoute = DieuKhoanDichVuRouteImport.update({
  id: '/dieu-khoan-dich-vu',
  path: '/dieu-khoan-dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const DichVuRoute = DichVuRouteImport.update({
  id: '/dich-vu',
  path: '/dich-vu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachVanChuyenRoute = ChinhSachVanChuyenRouteImport.update({
  id: '/chinh-sach-van-chuyen',
  path: '/chinh-sach-van-chuyen',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachDoiTraRoute = ChinhSachDoiTraRouteImport.update({
  id: '/chinh-sach-doi-tra',
  path: '/chinh-sach-doi-tra',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachBaoMatRoute = ChinhSachBaoMatRouteImport.update({
  id: '/chinh-sach-bao-mat',
  path: '/chinh-sach-bao-mat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachBaoHanhRoute = ChinhSachBaoHanhRouteImport.update({
  id: '/chinh-sach-bao-hanh',
  path: '/chinh-sach-bao-hanh',
  getParentRoute: () => rootRouteImport,
} as any)
const BoSuuTapRoute = BoSuuTapRouteImport.update({
  id: '/bo-suu-tap',
  path: '/bo-suu-tap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SanPhamSlugRoute = SanPhamSlugRouteImport.update({
  id: '/san-pham/$slug',
  path: '/san-pham/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bo-suu-tap': typeof BoSuuTapRoute
  '/chinh-sach-bao-hanh': typeof ChinhSachBaoHanhRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chinh-sach-doi-tra': typeof ChinhSachDoiTraRoute
  '/chinh-sach-van-chuyen': typeof ChinhSachVanChuyenRoute
  '/dich-vu': typeof DichVuRoute
  '/dieu-khoan-dich-vu': typeof DieuKhoanDichVuRoute
  '/don-hang': typeof DonHangRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/ho-tro': typeof HoTroRoute
  '/huong-dan-mua-hang': typeof HuongDanMuaHangRoute
  '/huong-dan-thanh-toan': typeof HuongDanThanhToanRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/thong-bao': typeof ThongBaoRoute
  '/thu-vong-co': typeof ThuVongCoRoute
  '/yeu-thich': typeof YeuThichRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bo-suu-tap': typeof BoSuuTapRoute
  '/chinh-sach-bao-hanh': typeof ChinhSachBaoHanhRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chinh-sach-doi-tra': typeof ChinhSachDoiTraRoute
  '/chinh-sach-van-chuyen': typeof ChinhSachVanChuyenRoute
  '/dich-vu': typeof DichVuRoute
  '/dieu-khoan-dich-vu': typeof DieuKhoanDichVuRoute
  '/don-hang': typeof DonHangRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/ho-tro': typeof HoTroRoute
  '/huong-dan-mua-hang': typeof HuongDanMuaHangRoute
  '/huong-dan-thanh-toan': typeof HuongDanThanhToanRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/thong-bao': typeof ThongBaoRoute
  '/thu-vong-co': typeof ThuVongCoRoute
  '/yeu-thich': typeof YeuThichRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bo-suu-tap': typeof BoSuuTapRoute
  '/chinh-sach-bao-hanh': typeof ChinhSachBaoHanhRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/chinh-sach-doi-tra': typeof ChinhSachDoiTraRoute
  '/chinh-sach-van-chuyen': typeof ChinhSachVanChuyenRoute
  '/dich-vu': typeof DichVuRoute
  '/dieu-khoan-dich-vu': typeof DieuKhoanDichVuRoute
  '/don-hang': typeof DonHangRoute
  '/gio-hang': typeof GioHangRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/ho-tro': typeof HoTroRoute
  '/huong-dan-mua-hang': typeof HuongDanMuaHangRoute
  '/huong-dan-thanh-toan': typeof HuongDanThanhToanRoute
  '/tai-khoan': typeof TaiKhoanRoute
  '/thanh-toan': typeof ThanhToanRoute
  '/thong-bao': typeof ThongBaoRoute
  '/thu-vong-co': typeof ThuVongCoRoute
  '/yeu-thich': typeof YeuThichRoute
  '/san-pham/$slug': typeof SanPhamSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bo-suu-tap'
    | '/chinh-sach-bao-hanh'
    | '/chinh-sach-bao-mat'
    | '/chinh-sach-doi-tra'
    | '/chinh-sach-van-chuyen'
    | '/dich-vu'
    | '/dieu-khoan-dich-vu'
    | '/don-hang'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/ho-tro'
    | '/huong-dan-mua-hang'
    | '/huong-dan-thanh-toan'
    | '/tai-khoan'
    | '/thanh-toan'
    | '/thong-bao'
    | '/thu-vong-co'
    | '/yeu-thich'
    | '/san-pham/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bo-suu-tap'
    | '/chinh-sach-bao-hanh'
    | '/chinh-sach-bao-mat'
    | '/chinh-sach-doi-tra'
    | '/chinh-sach-van-chuyen'
    | '/dich-vu'
    | '/dieu-khoan-dich-vu'
    | '/don-hang'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/ho-tro'
    | '/huong-dan-mua-hang'
    | '/huong-dan-thanh-toan'
    | '/tai-khoan'
    | '/thanh-toan'
    | '/thong-bao'
    | '/thu-vong-co'
    | '/yeu-thich'
    | '/san-pham/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bo-suu-tap'
    | '/chinh-sach-bao-hanh'
    | '/chinh-sach-bao-mat'
    | '/chinh-sach-doi-tra'
    | '/chinh-sach-van-chuyen'
    | '/dich-vu'
    | '/dieu-khoan-dich-vu'
    | '/don-hang'
    | '/gio-hang'
    | '/gioi-thieu'
    | '/ho-tro'
    | '/huong-dan-mua-hang'
    | '/huong-dan-thanh-toan'
    | '/tai-khoan'
    | '/thanh-toan'
    | '/thong-bao'
    | '/thu-vong-co'
    | '/yeu-thich'
    | '/san-pham/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BoSuuTapRoute: typeof BoSuuTapRoute
  ChinhSachBaoHanhRoute: typeof ChinhSachBaoHanhRoute
  ChinhSachBaoMatRoute: typeof ChinhSachBaoMatRoute
  ChinhSachDoiTraRoute: typeof ChinhSachDoiTraRoute
  ChinhSachVanChuyenRoute: typeof ChinhSachVanChuyenRoute
  DichVuRoute: typeof DichVuRoute
  DieuKhoanDichVuRoute: typeof DieuKhoanDichVuRoute
  DonHangRoute: typeof DonHangRoute
  GioHangRoute: typeof GioHangRoute
  GioiThieuRoute: typeof GioiThieuRoute
  HoTroRoute: typeof HoTroRoute
  HuongDanMuaHangRoute: typeof HuongDanMuaHangRoute
  HuongDanThanhToanRoute: typeof HuongDanThanhToanRoute
  TaiKhoanRoute: typeof TaiKhoanRoute
  ThanhToanRoute: typeof ThanhToanRoute
  ThongBaoRoute: typeof ThongBaoRoute
  ThuVongCoRoute: typeof ThuVongCoRoute
  YeuThichRoute: typeof YeuThichRoute
  SanPhamSlugRoute: typeof SanPhamSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yeu-thich': {
      id: '/yeu-thich'
      path: '/yeu-thich'
      fullPath: '/yeu-thich'
      preLoaderRoute: typeof YeuThichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thu-vong-co': {
      id: '/thu-vong-co'
      path: '/thu-vong-co'
      fullPath: '/thu-vong-co'
      preLoaderRoute: typeof ThuVongCoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thong-bao': {
      id: '/thong-bao'
      path: '/thong-bao'
      fullPath: '/thong-bao'
      preLoaderRoute: typeof ThongBaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thanh-toan': {
      id: '/thanh-toan'
      path: '/thanh-toan'
      fullPath: '/thanh-toan'
      preLoaderRoute: typeof ThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-khoan': {
      id: '/tai-khoan'
      path: '/tai-khoan'
      fullPath: '/tai-khoan'
      preLoaderRoute: typeof TaiKhoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan-thanh-toan': {
      id: '/huong-dan-thanh-toan'
      path: '/huong-dan-thanh-toan'
      fullPath: '/huong-dan-thanh-toan'
      preLoaderRoute: typeof HuongDanThanhToanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan-mua-hang': {
      id: '/huong-dan-mua-hang'
      path: '/huong-dan-mua-hang'
      fullPath: '/huong-dan-mua-hang'
      preLoaderRoute: typeof HuongDanMuaHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ho-tro': {
      id: '/ho-tro'
      path: '/ho-tro'
      fullPath: '/ho-tro'
      preLoaderRoute: typeof HoTroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gio-hang': {
      id: '/gio-hang'
      path: '/gio-hang'
      fullPath: '/gio-hang'
      preLoaderRoute: typeof GioHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don-hang': {
      id: '/don-hang'
      path: '/don-hang'
      fullPath: '/don-hang'
      preLoaderRoute: typeof DonHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-khoan-dich-vu': {
      id: '/dieu-khoan-dich-vu'
      path: '/dieu-khoan-dich-vu'
      fullPath: '/dieu-khoan-dich-vu'
      preLoaderRoute: typeof DieuKhoanDichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dich-vu': {
      id: '/dich-vu'
      path: '/dich-vu'
      fullPath: '/dich-vu'
      preLoaderRoute: typeof DichVuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-van-chuyen': {
      id: '/chinh-sach-van-chuyen'
      path: '/chinh-sach-van-chuyen'
      fullPath: '/chinh-sach-van-chuyen'
      preLoaderRoute: typeof ChinhSachVanChuyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-doi-tra': {
      id: '/chinh-sach-doi-tra'
      path: '/chinh-sach-doi-tra'
      fullPath: '/chinh-sach-doi-tra'
      preLoaderRoute: typeof ChinhSachDoiTraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-bao-mat': {
      id: '/chinh-sach-bao-mat'
      path: '/chinh-sach-bao-mat'
      fullPath: '/chinh-sach-bao-mat'
      preLoaderRoute: typeof ChinhSachBaoMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-bao-hanh': {
      id: '/chinh-sach-bao-hanh'
      path: '/chinh-sach-bao-hanh'
      fullPath: '/chinh-sach-bao-hanh'
      preLoaderRoute: typeof ChinhSachBaoHanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bo-suu-tap': {
      id: '/bo-suu-tap'
      path: '/bo-suu-tap'
      fullPath: '/bo-suu-tap'
      preLoaderRoute: typeof BoSuuTapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/san-pham/$slug': {
      id: '/san-pham/$slug'
      path: '/san-pham/$slug'
      fullPath: '/san-pham/$slug'
      preLoaderRoute: typeof SanPhamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BoSuuTapRoute: BoSuuTapRoute,
  ChinhSachBaoHanhRoute: ChinhSachBaoHanhRoute,
  ChinhSachBaoMatRoute: ChinhSachBaoMatRoute,
  ChinhSachDoiTraRoute: ChinhSachDoiTraRoute,
  ChinhSachVanChuyenRoute: ChinhSachVanChuyenRoute,
  DichVuRoute: DichVuRoute,
  DieuKhoanDichVuRoute: DieuKhoanDichVuRoute,
  DonHangRoute: DonHangRoute,
  GioHangRoute: GioHangRoute,
  GioiThieuRoute: GioiThieuRoute,
  HoTroRoute: HoTroRoute,
  HuongDanMuaHangRoute: HuongDanMuaHangRoute,
  HuongDanThanhToanRoute: HuongDanThanhToanRoute,
  TaiKhoanRoute: TaiKhoanRoute,
  ThanhToanRoute: ThanhToanRoute,
  ThongBaoRoute: ThongBaoRoute,
  ThuVongCoRoute: ThuVongCoRoute,
  YeuThichRoute: YeuThichRoute,
  SanPhamSlugRoute: SanPhamSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
